package com.svenruppert.imagerag.domain.enums;

public enum SensitivityFlag {
  PERSON_VISIBLE,
  CHILD_VISIBLE,
  LICENSE_PLATE_VISIBLE,
  READABLE_SIGN_OR_TEXT,
  ADDRESS_OR_LOCATION_HINT,
  PRIVATE_PROPERTY_HINT,
  EXIF_METADATA_PRESENT,
  GPS_DATA_PRESENT,
  NO_OBVIOUS_SENSITIVE_CONTENT
}
