package com.svenruppert.imagerag.domain.enums;

/**
 * Types of proposals generated by the taxonomy-maintenance workflow.
 * <p>Image-level suggestions target a specific image asset; taxonomy-level
 * suggestions target the category taxonomy itself (independent of any single image).
 */
public enum TaxonomySuggestionType {

  // ── Image-level suggestions ───────────────────────────────────────────────

  /**
   * Suggest reassigning an image from its current primary category to a different one.
   * Carries {@code currentCategory} → {@code suggestedCategory}.
   */
  RECLASSIFY_IMAGE,

  /**
   * Suggest adding a secondary (additional) category to an image that currently
   * lacks it.  Carries {@code suggestedCategory} as the category to add.
   */
  ADD_SECONDARY_CATEGORY,

  /**
   * Suggest removing an existing secondary category from an image because it no
   * longer fits or conflicts with the primary.  Carries {@code currentCategory}.
   */
  REMOVE_SECONDARY_CATEGORY,

  // ── Taxonomy-level suggestions ─────────────────────────────────────────────

  /**
   * Suggest deprecating an existing category.
   * May carry a {@code suggestedCategory} as a recommended replacement.
   */
  DEPRECATE_CATEGORY,

  /**
   * Suggest merging two overlapping categories into one.
   * {@code currentCategory} is the category to be absorbed;
   * {@code suggestedCategory} is the surviving target category.
   */
  MERGE_CATEGORIES,

  /**
   * Suggest adding an alias/synonym to an existing category so searches using
   * that term resolve to the right bucket.
   * Carries {@code currentCategory} and {@code suggestedAlias}.
   */
  ADD_ALIAS,

  /**
   * Suggest reassigning all images away from a deprecated/removed category.
   * Carries {@code currentCategory} (deprecated) and {@code suggestedCategory} (replacement).
   * Applied as a bulk migration action.
   */
  REASSIGN_DEPRECATED_CATEGORY
}
