package com.svenruppert.imagerag.service;

import com.svenruppert.imagerag.domain.TaxonomySuggestion;
import com.svenruppert.imagerag.domain.enums.SuggestionStatus;

import java.util.List;
import java.util.UUID;

/**
 * Manages the lifecycle of {@link TaxonomySuggestion} objects.
 *
 * <p>Suggestions are generated by {@link TaxonomyAnalysisService}.  This service
 * handles reviewing (accept / reject) and applying them — dispatching the
 * appropriate data mutation based on suggestion type.
 */
public interface TaxonomySuggestionService {

  /**
   * Marks a suggestion as {@link SuggestionStatus#ACCEPTED}.
   * Does nothing if the suggestion is not in OPEN state.
   */
  void accept(UUID suggestionId);

  /**
   * Marks a suggestion as {@link SuggestionStatus#REJECTED}.
   * Does nothing if the suggestion is already APPLIED.
   */
  void reject(UUID suggestionId);

  /**
   * Applies a suggestion: mutates the relevant domain objects, marks the suggestion
   * {@link SuggestionStatus#APPLIED}, and persists all changes.
   *
   * <p>The suggestion must be in OPEN or ACCEPTED state; REJECTED and APPLIED suggestions
   * are silently skipped.
   */
  void apply(UUID suggestionId);

  /**
   * Bulk-accept a list of suggestions.
   */
  void bulkAccept(List<UUID> suggestionIds);

  /**
   * Bulk-reject a list of suggestions.
   */
  void bulkReject(List<UUID> suggestionIds);

  /**
   * Bulk-apply: applies every suggestion whose id is in the list AND whose status
   * is OPEN or ACCEPTED.  Already-rejected or already-applied suggestions are skipped.
   *
   * @return number of suggestions that were actually applied
   */
  int bulkApply(List<UUID> suggestionIds);

  /**
   * Returns all stored suggestions.
   */
  List<TaxonomySuggestion> findAll();

  /**
   * Returns suggestions filtered by status.
   */
  List<TaxonomySuggestion> findByStatus(SuggestionStatus status);
}
