package com.svenruppert.imagerag.domain;

import com.svenruppert.imagerag.domain.enums.SourceCategory;

import java.time.Instant;
import java.util.*;

/**
 * A taxonomy-improvement suggestion derived from cluster analysis of the image inventory.
 * <p>EclipseStore-persisted (no-arg constructor, non-final fields, lazy-init via
 * {@link com.svenruppert.imagerag.persistence.AppDataRoot}).
 * <p>Cluster suggestions are generated by {@link com.svenruppert.imagerag.service.ClusterDiscoveryService}
 * and reviewed in the Taxonomy Maintenance view before being converted to
 * {@link TaxonomySuggestion} proposals or dismissed.
 */
public class CategoryClusterSuggestion {

  // ── Suggestion types ────────────────────────────────────────────────────

  private UUID id;
  private SuggestionType suggestionType;

  // ── Fields (EclipseStore-compatible: no final, no-arg constructor) ──────
  private ClusterSuggestionStatus status;
  private SourceCategory dominantCategory;
  /**
   * Cluster centroid description (generated heuristically from image tags/summaries).
   */
  private String clusterLabel;
  /**
   * Image IDs belonging to this cluster.
   */
  private List<UUID> imageIds;
  /**
   * Count of images per category in this cluster (key = SourceCategory.name()).
   */
  private Map<String, Integer> categoryDistribution;
  /**
   * Average intra-cluster cosine similarity (0–1).
   */
  private double intraClusterSimilarity;
  /**
   * Human-readable rationale generated by the discovery algorithm.
   */
  private String rationale;
  private Instant discoveredAt;
  /**
   * ID of the TaxonomySuggestion created from this cluster (after conversion).
   */
  private UUID convertedSuggestionId;

  public CategoryClusterSuggestion() {
  }

  public static CategoryClusterSuggestion create(
      SuggestionType type,
      SourceCategory dominantCategory,
      String clusterLabel,
      List<UUID> imageIds,
      Map<SourceCategory, Integer> categoryDist,
      double similarity,
      String rationale) {

    CategoryClusterSuggestion s = new CategoryClusterSuggestion();
    s.id = UUID.randomUUID();
    s.suggestionType = type;
    s.status = ClusterSuggestionStatus.OPEN;
    s.dominantCategory = dominantCategory;
    s.clusterLabel = clusterLabel;
    s.imageIds = new ArrayList<>(imageIds);
    s.categoryDistribution = new HashMap<>();
    categoryDist.forEach((cat, count) -> s.categoryDistribution.put(cat.name(), count));
    s.intraClusterSimilarity = similarity;
    s.rationale = rationale;
    s.discoveredAt = Instant.now();
    return s;
  }

  public UUID getId() {
    return id;
  }

  // ── Factory ─────────────────────────────────────────────────────────────

  public SuggestionType getSuggestionType() {
    return suggestionType;
  }

  // ── Accessors ───────────────────────────────────────────────────────────

  public ClusterSuggestionStatus getStatus() {
    return status;
  }

  public SourceCategory getDominantCategory() {
    return dominantCategory;
  }

  public String getClusterLabel() {
    return clusterLabel;
  }

  public List<UUID> getImageIds() {
    return imageIds != null ? imageIds : List.of();
  }

  public Map<String, Integer> getCategoryDistribution() {
    return categoryDistribution != null ? categoryDistribution : Map.of();
  }

  public double getIntraClusterSimilarity() {
    return intraClusterSimilarity;
  }

  public String getRationale() {
    return rationale;
  }

  public Instant getDiscoveredAt() {
    return discoveredAt;
  }

  public UUID getConvertedSuggestionId() {
    return convertedSuggestionId;
  }

  public void accept() {
    this.status = ClusterSuggestionStatus.ACCEPTED;
  }

  public void dismiss() {
    this.status = ClusterSuggestionStatus.DISMISSED;
  }

  // ── State transitions ───────────────────────────────────────────────────

  public void convert(UUID suggestionId) {
    this.status = ClusterSuggestionStatus.CONVERTED;
    this.convertedSuggestionId = suggestionId;
  }

  /**
   * Whether this suggestion spans multiple categories (merge/alias candidate).
   */
  public boolean isMultiCategory() {
    return categoryDistribution != null && categoryDistribution.size() > 1;
  }

  /**
   * Total number of images in this cluster.
   */
  public int clusterSize() {
    return imageIds != null ? imageIds.size() : 0;
  }

  public enum SuggestionType {
    PROPOSE_SUBCATEGORY("Propose new subcategory"),
    PROPOSE_SPLIT("Propose category split"),
    PROPOSE_MERGE("Propose category merge"),
    PROPOSE_ALIAS("Propose alias / synonym"),
    OUTLIER_RECLASSIFY("Outlier — likely misclassified");

    private final String label;

    SuggestionType(String l) {
      this.label = l;
    }

    public String getLabel() {
      return label;
    }
  }

  public enum ClusterSuggestionStatus {
    OPEN, ACCEPTED, DISMISSED, CONVERTED
  }
}
