package com.svenruppert.imagerag.domain;

import com.svenruppert.imagerag.domain.enums.SourceCategory;
import com.svenruppert.imagerag.domain.enums.SuggestionStatus;
import com.svenruppert.imagerag.domain.enums.TaxonomySuggestionType;

import java.time.Instant;
import java.util.UUID;

/**
 * A single reviewable taxonomy-maintenance proposal generated by the
 * {@link com.svenruppert.imagerag.service.TaxonomyAnalysisService}.
 *
 * <p>Suggestions are never applied automatically — the user must review and
 * explicitly accept/apply them in the Taxonomy Maintenance view.
 *
 * <p>Not declared final — EclipseStore Unsafe reconstruction compatibility.
 */
public class TaxonomySuggestion {

  /**
   * Unique identifier for this suggestion.
   */
  private UUID id;

  /**
   * What kind of change is being proposed.
   */
  private TaxonomySuggestionType type;

  /**
   * Review/apply lifecycle. Starts as {@link SuggestionStatus#OPEN}.
   */
  private SuggestionStatus status;

  // ── Image context (null for taxonomy-level suggestions) ───────────────────

  /**
   * The image this suggestion targets, or null for taxonomy-level suggestions.
   */
  private UUID targetImageId;

  /**
   * Original filename of the target image, for display without a separate lookup.
   */
  private String targetImageFilename;

  // ── Category context ──────────────────────────────────────────────────────

  /**
   * Current category value (before change). May be null for ADD_* types.
   */
  private SourceCategory currentCategory;

  /**
   * Proposed category (after change).
   * Null for DEPRECATE_CATEGORY when no replacement is suggested.
   */
  private SourceCategory suggestedCategory;

  /**
   * Proposed alias string.  Populated only for {@link TaxonomySuggestionType#ADD_ALIAS}.
   */
  private String suggestedAlias;

  // ── Rationale & confidence ────────────────────────────────────────────────

  /**
   * Human-readable explanation of why this suggestion was generated.
   */
  private String rationale;

  /**
   * Model-produced confidence in [0.0, 1.0] for this suggestion.
   * 1.0 = model is very sure; values below 0.6 are candidates for closer review.
   */
  private double confidence;

  /**
   * Which model/service generated this suggestion.
   */
  private String generatedByModel;

  // ── Timestamps ────────────────────────────────────────────────────────────

  private Instant createdAt;
  private Instant appliedAt;

  // ── Constructors ──────────────────────────────────────────────────────────

  public TaxonomySuggestion() {
    this.id = UUID.randomUUID();
    this.status = SuggestionStatus.OPEN;
    this.createdAt = Instant.now();
  }

  /**
   * Factory for image-level reclassification suggestions.
   */
  public static TaxonomySuggestion reclassify(UUID imageId,
                                              String imageFilename,
                                              SourceCategory current,
                                              SourceCategory suggested,
                                              double confidence,
                                              String rationale,
                                              String model) {
    TaxonomySuggestion s = new TaxonomySuggestion();
    s.type = TaxonomySuggestionType.RECLASSIFY_IMAGE;
    s.targetImageId = imageId;
    s.targetImageFilename = imageFilename;
    s.currentCategory = current;
    s.suggestedCategory = suggested;
    s.confidence = confidence;
    s.rationale = rationale;
    s.generatedByModel = model;
    return s;
  }

  /**
   * Factory for add-secondary-category suggestions.
   */
  public static TaxonomySuggestion addSecondary(UUID imageId,
                                                String imageFilename,
                                                SourceCategory suggested,
                                                double confidence,
                                                String rationale,
                                                String model) {
    TaxonomySuggestion s = new TaxonomySuggestion();
    s.type = TaxonomySuggestionType.ADD_SECONDARY_CATEGORY;
    s.targetImageId = imageId;
    s.targetImageFilename = imageFilename;
    s.suggestedCategory = suggested;
    s.confidence = confidence;
    s.rationale = rationale;
    s.generatedByModel = model;
    return s;
  }

  /**
   * Factory for taxonomy-level deprecation suggestions.
   */
  public static TaxonomySuggestion deprecate(SourceCategory toDeprecate,
                                             SourceCategory replacement,
                                             String rationale,
                                             String model) {
    TaxonomySuggestion s = new TaxonomySuggestion();
    s.type = TaxonomySuggestionType.DEPRECATE_CATEGORY;
    s.currentCategory = toDeprecate;
    s.suggestedCategory = replacement;
    s.confidence = 1.0;
    s.rationale = rationale;
    s.generatedByModel = model;
    return s;
  }

  /**
   * Factory for alias suggestions.
   */
  public static TaxonomySuggestion addAlias(SourceCategory category,
                                            String alias,
                                            String rationale,
                                            String model) {
    TaxonomySuggestion s = new TaxonomySuggestion();
    s.type = TaxonomySuggestionType.ADD_ALIAS;
    s.currentCategory = category;
    s.suggestedAlias = alias;
    s.confidence = 0.8;
    s.rationale = rationale;
    s.generatedByModel = model;
    return s;
  }

  /**
   * Factory for bulk reassign-deprecated suggestions.
   */
  public static TaxonomySuggestion reassignDeprecated(UUID imageId,
                                                      String imageFilename,
                                                      SourceCategory deprecated,
                                                      SourceCategory replacement,
                                                      String model) {
    TaxonomySuggestion s = new TaxonomySuggestion();
    s.type = TaxonomySuggestionType.REASSIGN_DEPRECATED_CATEGORY;
    s.targetImageId = imageId;
    s.targetImageFilename = imageFilename;
    s.currentCategory = deprecated;
    s.suggestedCategory = replacement;
    s.confidence = 1.0;
    s.rationale = "Image assigned to deprecated category " + deprecated + "; reassigning to " + replacement;
    s.generatedByModel = model;
    return s;
  }

  // ── Accessors ──────────────────────────────────────────────────────────────

  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public TaxonomySuggestionType getType() {
    return type;
  }

  public void setType(TaxonomySuggestionType type) {
    this.type = type;
  }

  public SuggestionStatus getStatus() {
    return status != null ? status : SuggestionStatus.OPEN;
  }

  public void setStatus(SuggestionStatus status) {
    this.status = status;
  }

  public UUID getTargetImageId() {
    return targetImageId;
  }

  public void setTargetImageId(UUID targetImageId) {
    this.targetImageId = targetImageId;
  }

  public String getTargetImageFilename() {
    return targetImageFilename;
  }

  public void setTargetImageFilename(String targetImageFilename) {
    this.targetImageFilename = targetImageFilename;
  }

  public SourceCategory getCurrentCategory() {
    return currentCategory;
  }

  public void setCurrentCategory(SourceCategory currentCategory) {
    this.currentCategory = currentCategory;
  }

  public SourceCategory getSuggestedCategory() {
    return suggestedCategory;
  }

  public void setSuggestedCategory(SourceCategory suggestedCategory) {
    this.suggestedCategory = suggestedCategory;
  }

  public String getSuggestedAlias() {
    return suggestedAlias;
  }

  public void setSuggestedAlias(String suggestedAlias) {
    this.suggestedAlias = suggestedAlias;
  }

  public String getRationale() {
    return rationale;
  }

  public void setRationale(String rationale) {
    this.rationale = rationale;
  }

  public double getConfidence() {
    return confidence;
  }

  public void setConfidence(double confidence) {
    this.confidence = Math.max(0.0, Math.min(1.0, confidence));
  }

  public String getGeneratedByModel() {
    return generatedByModel;
  }

  public void setGeneratedByModel(String generatedByModel) {
    this.generatedByModel = generatedByModel;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }

  public Instant getAppliedAt() {
    return appliedAt;
  }

  public void setAppliedAt(Instant appliedAt) {
    this.appliedAt = appliedAt;
  }

  /**
   * Returns true if this is an image-level suggestion (has a target image).
   */
  public boolean isImageLevel() {
    return targetImageId != null;
  }
}
